[workspace]
members = [".", "crates/core"]
resolver = "2"

[package]
name = "r_tvui"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = "0.30.0"
crossterm = "0.29"
rtvui-core = { path = "crates/core", package = "core" }
clap = { version = "4.6.1", features = ["derive"] }
config = { version = "0.15.23", features = ["toml"] }
serde = { version = "1.0.228", features = ["derive"] }
dirs = "6.0.0"
toml = "1.1.2"
tokio = { version = "1.52.3", features = ["rt-multi-thread", "macros", "sync", "fs", "time"] }
tempfile = "3.10.0"
shellexpand = "3.1.2"
trash = "5"
arboard = "3.6.1"
