name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  
  
  deploy:
    strategy:
      fail-fast: false
      matrix:
        include:
          - command: fmt
          - command: check
          - command: lint
          - command: clean
          - command: test
          - command: build

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy
    - name: ${{ matrix.command }}
      run: make ${{ matrix.command }}
